# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
# Gems
gems: [jekyll-paginate]

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: kaoraswoo
google_analytics: kaoraswoo
url: http://kaoraswoo.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 스우의 게임서버와 클라이언트!

description: kaoraswoo gameserver and client
author:
  name: kaoraswoo
  email: kaoraswoo@naver.com
  github: kaoraswoo
  linkedin: kaoraswoo
  bio: 스우의 게임서버와 클라이언트!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

